name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# For the test job, I use environment variables to point to an in-memory test DB.
env:
  DATABASE_URL: "sqlite:///:memory:"
  SECRET_KEY: "test-secret-key"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio alembic

      # No migrations are run in the test job against the test DB.
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml --cov-report=term-missing
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          SECRET_KEY: ${{ env.SECRET_KEY }}

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install production dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary alembic uvicorn fastapi

      - name: Run production database migrations
        run: |
          # Run only the upgrade command against the production DB.
          alembic upgrade head
        env:
          # Use remote production database credentials from secrets.
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bookmark-manager-api:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bookmark-manager-api:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bookmark-manager-api
          region: europe-southwest1
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bookmark-manager-api:latest
          flags: |
            --set-env-vars=SECRET_KEY=${{ secrets.SECRET_KEY }}
            --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}
            --set-env-vars=ALGORITHM=HS256
            --set-env-vars=ACCESS_TOKEN_EXPIRE_MINUTES=120
